module.exports = [
    require('./base.css'),
    require('./button.css'),
    require('./color.css'),
    require('./dialog.css'),
    require('./input.css'),
    require('./layout.css'),
    require('./menu.css'),
    require('./misc.css'),
    require('./number.css'),
    require('./progress.css'),
    require('./select.css'),
    require('./tracker.css'),
    require('./toggle.css'),
];
