"""Multi-factor authentication with time-based one-time passwords.

The adapter checks TOTP codes generated by authenticator apps. The secret is
taken from the ``mfaSecret`` attribute of the user; users without it cannot
start a transaction. The client sends the code as ``{"code": ...}``.
``key_uri`` creates a key URI for a secret, which can be shown as a QR code to
set up the app.

Example::

    auth.mfa+ {
        type "totp"
        uid "AUTH_MFA_TOTP"
    }
"""

import gws
import gws.base.auth
import gws.lib.net
import gws.lib.otp


@gws.ext.config.authMultiFactorAdapter('totp')
class Config(gws.base.auth.mfa.Config):
    """Multi-factor authentication with time-based one-time passwords."""

    pass


@gws.ext.object.authMultiFactorAdapter('totp')
class Object(gws.base.auth.mfa.Object):
    """TOTP multi-factor adapter."""

    def start(self, user):
        if not user.mfaSecret:
            gws.log.warning(f'totp: cannot start, {user.uid=}: no secret')
            return

        mfa = super().start(user)
        mfa.secret = user.mfaSecret

        return mfa

    def verify(self, mfa, payload):
        ok = self.check_totp(mfa, payload.get('code'))
        return self.verify_attempt(mfa, ok)

    def key_uri(self, secret, issuer_name, account_name):
        return gws.lib.otp.totp_key_uri(secret, issuer_name, account_name, self.otpOptions)
