import sys
import gws


def main(args: gws.TemplateArgs):
    text = f"""
        This output is generated by python:

        {sys.version}

        Template arguments:
            - Project title: {args.project.title.upper()}
            - Version: {args.app.version}
            - User uid: {args.user.uid}

    """

    return gws.ContentResponse(
        mime='text/plain',
        content=text,
    )
