#!/usr/bin/env bash

## generated by install/qgis/prepare.py, do not edit

cd /root/QGIS/_BUILD

if [ "$1" == "configure" ]; then
shift
rm -fr /root/QGIS/_BUILD/*
cmake \
-D BUILD_TESTING:BOOL=OFF \
-D CMAKE_BUILD_TYPE:STRING=$1 \
-D CMAKE_VERBOSE_MAKEFILE:BOOL=TRUE \
-D ENABLE_TESTS:BOOL=FALSE \
-D PEDANTIC:BOOL=FALSE \
-D WITH_DESKTOP:BOOL=FALSE \
-D WITH_EPT:BOOL=FALSE \
-D WITH_GRASS7:BOOL=FALSE \
-D WITH_GRASS8:BOOL=FALSE \
-D WITH_GSL:BOOL=FALSE \
-D WITH_HANA:BOOL=FALSE \
-D WITH_QGIS_PROCESS:BOOL=FALSE \
-D WITH_QSCIAPI:BOOL=FALSE \
-D WITH_QSPATIALITE:BOOL=TRUE \
-D WITH_QT5SERIALPORT:BOOL=FALSE \
-D WITH_SERVER:BOOL=TRUE \
..
fi

if [ "$1" == "package" ]; then
shift

rm -fr qgis-for-gws
mkdir -p qgis-for-gws/usr

# libraries
cp -vr output/lib qgis-for-gws/usr

# server
mkdir -p qgis-for-gws/usr/bin
cp -v output/bin/qgis_mapserv.fcgi qgis-for-gws/usr/bin

# python (qgis package only)
mkdir -p qgis-for-gws/usr/lib/python3/dist-packages
cp -vr output/python/qgis qgis-for-gws/usr/lib/python3/dist-packages

# resources (no depth)
mkdir -p qgis-for-gws/usr/share/qgis/resources
cp -v  ../resources/* qgis-for-gws/usr/share/qgis/resources
cp -vr ../resources/server qgis-for-gws/usr/share/qgis/resources

# svg's
cp -vr  ../images/svg qgis-for-gws/usr/share/qgis

# license
cp ../COPYING qgis-for-gws/usr/lib
    
# delete lib symlinks
find qgis-for-gws -type l -exec rm -vfr {} \;

# delete python caches
find qgis-for-gws -depth -name __pycache__ -exec rm -vfr {} \;
fi
