import os.path
import re

wd = os.path.dirname(os.path.realpath(__file__))

cvars = []
with open(wd + '/vars.txt') as fp:
    for s in fp:
        m = re.match(r'(.+?)=(.*?)@(.+)', s)
        if m:
            cvars.append('-D %s=%s' % (m.group(1).strip(), m.group(3).strip()))
cvars = ' \\\n'.join(cvars)

build = '/root/QGIS/_BUILD'
pkg = 'qgis-for-gws'

script = f"""\
#!/usr/bin/env bash

## generated by install/qgis/prepare.py, do not edit

cd {build}

if [ "$1" == "configure" ]; then
shift
rm -fr {build}/*
cmake \\
{cvars} \\
..
fi

if [ "$1" == "package" ]; then
shift

rm -fr {pkg}
mkdir -p {pkg}/usr

# libraries
cp -vr output/lib {pkg}/usr

# server
mkdir -p {pkg}/usr/bin
cp -v output/bin/qgis_mapserv.fcgi {pkg}/usr/bin

# python (qgis package only)
mkdir -p {pkg}/usr/lib/python3/dist-packages
cp -vr output/python/qgis {pkg}/usr/lib/python3/dist-packages

# resources (no depth)
mkdir -p {pkg}/usr/share/qgis/resources
cp -v  ../resources/* {pkg}/usr/share/qgis/resources
cp -vr ../resources/server {pkg}/usr/share/qgis/resources

# svg's
cp -vr  ../images/svg {pkg}/usr/share/qgis

# license
cp ../COPYING {pkg}/usr/lib
    
# delete lib symlinks
find {pkg} -type l -exec rm -vfr {{}} \\;

# delete python caches
find {pkg} -depth -name __pycache__ -exec rm -vfr {{}} \\;
fi
"""

with open(wd + '/gws.sh', 'wt') as fp:
    fp.write(script)
