"""Well-known XML namespaces.

Module-level constants with uppercase names (``OWS_11``, ``GML``); use as ``namespace.c.WFS``.
"""

import gws


def _ns(prefix: str, uri: str, schema: str = '') -> gws.XmlNamespace:
    return gws.XmlNamespace(prefix=prefix, uri=uri, schemaLocation=schema, extendsGml=False)


HTML = _ns('html', 'http://www.w3.org/1999/xhtml')
RDF = _ns('rdf', 'http://www.w3.org/1999/02/22-rdf-syntax-ns')
SOAP = _ns('soap', 'http://www.w3.org/2003/05/soap-envelope', 'http://www.w3.org/2003/05/soap-envelope/')
SOAP_11 = _ns('soap11', 'http://schemas.xmlsoap.org/soap/envelope/')
WSDL = _ns('wsdl', 'http://schemas.xmlsoap.org/wsdl')
XLINK = _ns('xlink', 'http://www.w3.org/1999/xlink', 'http://www.w3.org/1999/xlink.xsd')
XML = _ns('xml', 'http://www.w3.org/XML/1998/namespace')
XSD = _ns('xsd', 'http://www.w3.org/2001/XMLSchema', 'http://www.w3.org/2001/XMLSchema.xsd')
XSI = _ns('xsi', 'http://www.w3.org/2001/XMLSchema-instance')

CSW = _ns('csw', 'http://www.opengis.net/cat/csw/2.0.2', 'http://schemas.opengis.net/csw/2.0.2/CSW-discovery.xsd')
FES = _ns('fes', 'http://www.opengis.net/fes/2.0', 'http://schemas.opengis.net/filter/2.0/filterAll.xsd')
GML = _ns('gml', 'http://www.opengis.net/gml/3.2', 'http://schemas.opengis.net/gml/3.2.1/gml.xsd')
GML_2 = _ns('gml', 'http://www.opengis.net/gml', 'http://schemas.opengis.net/gml/2.1.2/gml.xsd')
GML_3_1 = _ns('gml', 'http://www.opengis.net/gml', 'http://schemas.opengis.net/gml/3.1.1/base/gml.xsd')
GMLCOV = _ns('gmlcov', 'http://www.opengis.net/gmlcov/1.0', 'http://schemas.opengis.net/gmlcov/1.0/gmlcovAll.xsd')
OGC = _ns('ogc', 'http://www.opengis.net/ogc', 'http://schemas.opengis.net/filter/1.1.0/filter.xsd')
OWS = _ns('ows', 'http://www.opengis.net/ows/2.0', 'http://schemas.opengis.net/ows/2.0/owsAll.xsd')
OWS_0 = _ns('ows', 'http://www.opengis.net/ows', 'http://schemas.opengis.net/ows/1.1.0/owsAll.xsd')
OWS_11 = _ns('ows', 'http://www.opengis.net/ows/1.1', 'http://schemas.opengis.net/ows/1.1.0/owsAll.xsd')
SLD = _ns('sld', 'http://www.opengis.net/sld', 'http://schemas.opengis.net/sld/1.1/sldAll.xsd')
SWE = _ns('swe', 'http://www.opengis.net/swe/2.0', 'http://schemas.opengis.net/sweCommon/2.0/swe.xsd')
WCS = _ns('wcs', 'http://www.opengis.net/wcs/2.0', 'http://schemas.opengis.net/wcs/1.0.0/wcsAll.xsd')
WCSCRS = _ns('wcscrs', 'http://www.opengis.net/wcs/crs/1.0')
WCSINT = _ns('wcsint', 'http://www.opengis.net/wcs/interpolation/1.0')
WCSSCAL = _ns('wcsscal', 'http://www.opengis.net/wcs/scaling/1.0')
WFS = _ns('wfs', 'http://www.opengis.net/wfs/2.0', 'http://schemas.opengis.net/wfs/2.0/wfs.xsd')
WFS_11 = _ns('wfs', 'http://www.opengis.net/wfs', 'http://schemas.opengis.net/wfs/1.1.0/wfs.xsd')
WMS = _ns('wms', 'http://www.opengis.net/wms', 'http://schemas.opengis.net/wms/1.3.0/capabilities_1_3_0.xsd')
WMTS = _ns('wmts', 'http://www.opengis.net/wmts/1.0', 'http://schemas.opengis.net/wmts/1.0/wmts.xsd')

GCO = _ns('gco', 'http://www.isotc211.org/2005/gco', 'http://schemas.opengis.net/iso/19139/20070417/gco/gco.xsd')
GMD = _ns('gmd', 'http://www.isotc211.org/2005/gmd', 'http://schemas.opengis.net/iso/19139/20070417/gmd/gmd.xsd')
GMX = _ns('gmx', 'http://www.isotc211.org/2005/gmx', 'http://schemas.opengis.net/iso/19139/20070417/gmx/gmx.xsd')
SRV = _ns('srv', 'http://www.isotc211.org/2005/srv', 'http://schemas.opengis.net/iso/19139/20070417/srv/1.0/srv.xsd')
DC = _ns('dc', 'http://purl.org/dc/elements/1.1/', 'http://schemas.opengis.net/csw/2.0.2/rec-dcmes.xsd')
DCM = _ns('dcm', 'http://purl.org/dc/dcmitype/', 'http://dublincore.org/schemas/xmls/qdc/2008/02/11/dcmitype.xsd')
DCT = _ns('dct', 'http://purl.org/dc/terms/', 'http://schemas.opengis.net/csw/2.0.2/rec-dcterms.xsd')
MS = _ns('ms', 'http://mapserver.gis.umn.edu/mapserver')

INSPIRE_DLS = _ns('inspire_dls', 'http://inspire.ec.europa.eu/schemas/inspire_dls/1.0', 'http://inspire.ec.europa.eu/schemas/inspire_dls/1.0/inspire_dls.xsd')
INSPIRE_DS = _ns('inspire_ds', 'http://inspire.ec.europa.eu/schemas/inspire_ds/1.0', 'http://inspire.ec.europa.eu/schemas/inspire_ds/1.0/inspire_ds.xsd')
INSPIRE_VS = _ns('inspire_vs', 'http://inspire.ec.europa.eu/schemas/inspire_vs/1.0', 'http://inspire.ec.europa.eu/schemas/inspire_vs/1.0/inspire_vs.xsd')
INSPIRE_VS_OWS_11 = _ns('inspire_vs_ows11', 'http://inspire.ec.europa.eu/schemas/inspire_vs_ows11/1.0', 'http://inspire.ec.europa.eu/schemas/inspire_vs_ows11/1.0/inspire_vs_ows_11.xsd')
INSPIRE_COMMON = _ns('inspire_common', 'http://inspire.ec.europa.eu/schemas/common/1.0', 'http://inspire.ec.europa.eu/schemas/common/1.0/common.xsd')
INSPIRE_AC_MF = _ns('ac-mf', 'http://inspire.ec.europa.eu/schemas/ac-mf/4.0', 'http://inspire.ec.europa.eu/schemas/ac-mf/4.0/AtmosphericConditionsandMeteorologicalGeographicalFeatures.xsd')
INSPIRE_ACT_CORE = _ns('act-core', 'http://inspire.ec.europa.eu/schemas/act-core/4.0', 'http://inspire.ec.europa.eu/schemas/act-core/4.0/ActivityComplex_Core.xsd')
INSPIRE_AD = _ns('ad', 'http://inspire.ec.europa.eu/schemas/ad/4.0', 'http://inspire.ec.europa.eu/schemas/ad/4.0/Addresses.xsd')
INSPIRE_AF = _ns('af', 'http://inspire.ec.europa.eu/schemas/af/4.0', 'http://inspire.ec.europa.eu/schemas/af/4.0/AgriculturalAndAquacultureFacilities.xsd')
INSPIRE_AM = _ns('am', 'http://inspire.ec.europa.eu/schemas/am/4.0', 'http://inspire.ec.europa.eu/schemas/am/4.0/AreaManagementRestrictionRegulationZone.xsd')
INSPIRE_AU = _ns('au', 'http://inspire.ec.europa.eu/schemas/au/4.0', 'http://inspire.ec.europa.eu/schemas/au/4.0/AdministrativeUnits.xsd')
INSPIRE_BASE = _ns('base', 'http://inspire.ec.europa.eu/schemas/base/3.3', 'http://inspire.ec.europa.eu/schemas/base/3.3/BaseTypes.xsd')
INSPIRE_BASE2 = _ns('base2', 'http://inspire.ec.europa.eu/schemas/base2/2.0', 'http://inspire.ec.europa.eu/schemas/base2/2.0/BaseTypes2.xsd')
INSPIRE_BR = _ns('br', 'http://inspire.ec.europa.eu/schemas/br/4.0', 'http://inspire.ec.europa.eu/schemas/br/4.0/Bio-geographicalRegions.xsd')
INSPIRE_BU_BASE = _ns('bu-base', 'http://inspire.ec.europa.eu/schemas/bu-base/4.0', 'http://inspire.ec.europa.eu/schemas/bu-base/4.0/BuildingsBase.xsd')
INSPIRE_BU_CORE2D = _ns('bu-core2d', 'http://inspire.ec.europa.eu/schemas/bu-core2d/4.0', 'http://inspire.ec.europa.eu/schemas/bu-core2d/4.0/BuildingsCore2D.xsd')
INSPIRE_BU_CORE3D = _ns('bu-core3d', 'http://inspire.ec.europa.eu/schemas/bu-core3d/4.0', 'http://inspire.ec.europa.eu/schemas/bu-core3d/4.0/BuildingsCore3D.xsd')
INSPIRE_BU = _ns('bu', 'http://inspire.ec.europa.eu/schemas/bu/0.0', 'http://inspire.ec.europa.eu/schemas/bu/0.0/Buildings.xsd')
INSPIRE_CP = _ns('cp', 'http://inspire.ec.europa.eu/schemas/cp/4.0', 'http://inspire.ec.europa.eu/schemas/cp/4.0/CadastralParcels.xsd')
INSPIRE_CVBASE = _ns('cvbase', 'http://inspire.ec.europa.eu/schemas/cvbase/2.0', 'http://inspire.ec.europa.eu/schemas/cvbase/2.0/CoverageBase.xsd')
INSPIRE_CVGVP = _ns('cvgvp', 'http://inspire.ec.europa.eu/schemas/cvgvp/0.1', 'http://inspire.ec.europa.eu/schemas/cvgvp/0.1/CoverageGVP.xsd')
INSPIRE_EF = _ns('ef', 'http://inspire.ec.europa.eu/schemas/ef/4.0', 'http://inspire.ec.europa.eu/schemas/ef/4.0/EnvironmentalMonitoringFacilities.xsd')
INSPIRE_EL_BAS = _ns('el-bas', 'http://inspire.ec.europa.eu/schemas/el-bas/4.0', 'http://inspire.ec.europa.eu/schemas/el-bas/4.0/ElevationBaseTypes.xsd')
INSPIRE_EL_COV = _ns('el-cov', 'http://inspire.ec.europa.eu/schemas/el-cov/4.0', 'http://inspire.ec.europa.eu/schemas/el-cov/4.0/ElevationGridCoverage.xsd')
INSPIRE_EL_TIN = _ns('el-tin', 'http://inspire.ec.europa.eu/schemas/el-tin/4.0', 'http://inspire.ec.europa.eu/schemas/el-tin/4.0/ElevationTin.xsd')
INSPIRE_EL_VEC = _ns('el-vec', 'http://inspire.ec.europa.eu/schemas/el-vec/4.0', 'http://inspire.ec.europa.eu/schemas/el-vec/4.0/ElevationVectorElements.xsd')
INSPIRE_ELU = _ns('elu', 'http://inspire.ec.europa.eu/schemas/elu/4.0', 'http://inspire.ec.europa.eu/schemas/elu/4.0/ExistingLandUse.xsd')
INSPIRE_ER_B = _ns('er-b', 'http://inspire.ec.europa.eu/schemas/er-b/4.0', 'http://inspire.ec.europa.eu/schemas/er-b/4.0/EnergyResourcesBase.xsd')
INSPIRE_ER_C = _ns('er-c', 'http://inspire.ec.europa.eu/schemas/er-c/4.0', 'http://inspire.ec.europa.eu/schemas/er-c/4.0/EnergyResourcesCoverage.xsd')
INSPIRE_ER_V = _ns('er-v', 'http://inspire.ec.europa.eu/schemas/er-v/4.0', 'http://inspire.ec.europa.eu/schemas/er-v/4.0/EnergyResourcesVector.xsd')
INSPIRE_ER = _ns('er', 'http://inspire.ec.europa.eu/schemas/er/0.0', 'http://inspire.ec.europa.eu/schemas/er/0.0/EnergyResources.xsd')
INSPIRE_GAZ = _ns('gaz', 'http://inspire.ec.europa.eu/schemas/gaz/3.2', 'http://inspire.ec.europa.eu/schemas/gaz/3.2/Gazetteer.xsd')
INSPIRE_GE_CORE = _ns('ge-core', 'http://inspire.ec.europa.eu/schemas/ge-core/4.0', 'http://inspire.ec.europa.eu/schemas/ge-core/4.0/GeologyCore.xsd')
INSPIRE_GE = _ns('ge', 'http://inspire.ec.europa.eu/schemas/ge/0.0', 'http://inspire.ec.europa.eu/schemas/ge/0.0/Geology.xsd')
INSPIRE_GE_GP = _ns('ge_gp', 'http://inspire.ec.europa.eu/schemas/ge_gp/4.0', 'http://inspire.ec.europa.eu/schemas/ge_gp/4.0/GeophysicsCore.xsd')
INSPIRE_GE_HG = _ns('ge_hg', 'http://inspire.ec.europa.eu/schemas/ge_hg/4.0', 'http://inspire.ec.europa.eu/schemas/ge_hg/4.0/HydrogeologyCore.xsd')
INSPIRE_GELU = _ns('gelu', 'http://inspire.ec.europa.eu/schemas/gelu/4.0', 'http://inspire.ec.europa.eu/schemas/gelu/4.0/GriddedExistingLandUse.xsd')
INSPIRE_GEOPORTAL = _ns('geoportal', 'http://inspire.ec.europa.eu/schemas/geoportal/1.0', 'http://inspire.ec.europa.eu/schemas/geoportal/1.0/geoportal.xsd')
INSPIRE_GN = _ns('gn', 'http://inspire.ec.europa.eu/schemas/gn/4.0', 'http://inspire.ec.europa.eu/schemas/gn/4.0/GeographicalNames.xsd')
INSPIRE_HB = _ns('hb', 'http://inspire.ec.europa.eu/schemas/hb/4.0', 'http://inspire.ec.europa.eu/schemas/hb/4.0/HabitatsAndBiotopes.xsd')
INSPIRE_HH = _ns('hh', 'http://inspire.ec.europa.eu/schemas/hh/4.0', 'http://inspire.ec.europa.eu/schemas/hh/4.0/HumanHealth.xsd')
INSPIRE_HY_N = _ns('hy-n', 'http://inspire.ec.europa.eu/schemas/hy-n/4.0', 'http://inspire.ec.europa.eu/schemas/hy-n/4.0/HydroNetwork.xsd')
INSPIRE_HY_P = _ns('hy-p', 'http://inspire.ec.europa.eu/schemas/hy-p/4.0', 'http://inspire.ec.europa.eu/schemas/hy-p/4.0/HydroPhysicalWaters.xsd')
INSPIRE_HY = _ns('hy', 'http://inspire.ec.europa.eu/schemas/hy/4.0', 'http://inspire.ec.europa.eu/schemas/hy/4.0/HydroBase.xsd')
INSPIRE_LC = _ns('lc', 'http://inspire.ec.europa.eu/schemas/lc/0.0', 'http://inspire.ec.europa.eu/schemas/lc/0.0/LandCover.xsd')
INSPIRE_LCN = _ns('lcn', 'http://inspire.ec.europa.eu/schemas/lcn/4.0', 'http://inspire.ec.europa.eu/schemas/lcn/4.0/LandCoverNomenclature.xsd')
INSPIRE_LCR = _ns('lcr', 'http://inspire.ec.europa.eu/schemas/lcr/4.0', 'http://inspire.ec.europa.eu/schemas/lcr/4.0/LandCoverRaster.xsd')
INSPIRE_LCV = _ns('lcv', 'http://inspire.ec.europa.eu/schemas/lcv/4.0', 'http://inspire.ec.europa.eu/schemas/lcv/4.0/LandCoverVector.xsd')
INSPIRE_LUNOM = _ns('lunom', 'http://inspire.ec.europa.eu/schemas/lunom/4.0', 'http://inspire.ec.europa.eu/schemas/lunom/4.0/LandUseNomenclature.xsd')
INSPIRE_MR_CORE = _ns('mr-core', 'http://inspire.ec.europa.eu/schemas/mr-core/4.0', 'http://inspire.ec.europa.eu/schemas/mr-core/4.0/MineralResourcesCore.xsd')
INSPIRE_MU = _ns('mu', 'http://inspire.ec.europa.eu/schemas/mu/4.0', 'http://inspire.ec.europa.eu/schemas/mu/4.0/MaritimeUnits.xsd')
INSPIRE_NET = _ns('net', 'http://inspire.ec.europa.eu/schemas/net/4.0', 'http://inspire.ec.europa.eu/schemas/net/4.0/Network.xsd')
INSPIRE_NZ_CORE = _ns('nz-core', 'http://inspire.ec.europa.eu/schemas/nz-core/4.0', 'http://inspire.ec.europa.eu/schemas/nz-core/4.0/NaturalRiskZonesCore.xsd')
INSPIRE_NZ = _ns('nz', 'http://inspire.ec.europa.eu/schemas/nz/0.0', 'http://inspire.ec.europa.eu/schemas/nz/0.0/NaturalRiskZones.xsd')
INSPIRE_OF = _ns('of', 'http://inspire.ec.europa.eu/schemas/of/4.0', 'http://inspire.ec.europa.eu/schemas/of/4.0/OceanFeatures.xsd')
INSPIRE_OI = _ns('oi', 'http://inspire.ec.europa.eu/schemas/oi/4.0', 'http://inspire.ec.europa.eu/schemas/oi/4.0/Orthoimagery.xsd')
INSPIRE_OMOP = _ns('omop', 'http://inspire.ec.europa.eu/schemas/omop/3.0', 'http://inspire.ec.europa.eu/schemas/omop/3.0/ObservableProperties.xsd')
INSPIRE_OMOR = _ns('omor', 'http://inspire.ec.europa.eu/schemas/omor/3.0', 'http://inspire.ec.europa.eu/schemas/omor/3.0/ObservationReferences.xsd')
INSPIRE_OMPR = _ns('ompr', 'http://inspire.ec.europa.eu/schemas/ompr/3.0', 'http://inspire.ec.europa.eu/schemas/ompr/3.0/Processes.xsd')
INSPIRE_OMSO = _ns('omso', 'http://inspire.ec.europa.eu/schemas/omso/3.0', 'http://inspire.ec.europa.eu/schemas/omso/3.0/SpecialisedObservations.xsd')
INSPIRE_PD = _ns('pd', 'http://inspire.ec.europa.eu/schemas/pd/4.0', 'http://inspire.ec.europa.eu/schemas/pd/4.0/PopulationDistributionDemography.xsd')
INSPIRE_PF = _ns('pf', 'http://inspire.ec.europa.eu/schemas/pf/4.0', 'http://inspire.ec.europa.eu/schemas/pf/4.0/ProductionAndIndustrialFacilities.xsd')
INSPIRE_PLU = _ns('plu', 'http://inspire.ec.europa.eu/schemas/plu/4.0', 'http://inspire.ec.europa.eu/schemas/plu/4.0/PlannedLandUse.xsd')
INSPIRE_PS = _ns('ps', 'http://inspire.ec.europa.eu/schemas/ps/4.0', 'http://inspire.ec.europa.eu/schemas/ps/4.0/ProtectedSites.xsd')
INSPIRE_SD = _ns('sd', 'http://inspire.ec.europa.eu/schemas/sd/4.0', 'http://inspire.ec.europa.eu/schemas/sd/4.0/SpeciesDistribution.xsd')
INSPIRE_SELU = _ns('selu', 'http://inspire.ec.europa.eu/schemas/selu/4.0', 'http://inspire.ec.europa.eu/schemas/selu/4.0/SampledExistingLandUse.xsd')
INSPIRE_SO = _ns('so', 'http://inspire.ec.europa.eu/schemas/so/4.0', 'http://inspire.ec.europa.eu/schemas/so/4.0/Soil.xsd')
INSPIRE_SR = _ns('sr', 'http://inspire.ec.europa.eu/schemas/sr/4.0', 'http://inspire.ec.europa.eu/schemas/sr/4.0/SeaRegions.xsd')
INSPIRE_SU_CORE = _ns('su-core', 'http://inspire.ec.europa.eu/schemas/su-core/4.0', 'http://inspire.ec.europa.eu/schemas/su-core/4.0/StatisticalUnitCore.xsd')
INSPIRE_SU_GRID = _ns('su-grid', 'http://inspire.ec.europa.eu/schemas/su-grid/4.0', 'http://inspire.ec.europa.eu/schemas/su-grid/4.0/StatisticalUnitGrid.xsd')
INSPIRE_SU_VECTOR = _ns('su-vector', 'http://inspire.ec.europa.eu/schemas/su-vector/4.0', 'http://inspire.ec.europa.eu/schemas/su-vector/4.0/StatisticalUnitVector.xsd')
INSPIRE_SU = _ns('su', 'http://inspire.ec.europa.eu/schemas/su/0.0', 'http://inspire.ec.europa.eu/schemas/su/0.0/StatisticalUnits.xsd')
INSPIRE_TN_A = _ns('tn-a', 'http://inspire.ec.europa.eu/schemas/tn-a/4.0', 'http://inspire.ec.europa.eu/schemas/tn-a/4.0/AirTransportNetwork.xsd')
INSPIRE_TN_C = _ns('tn-c', 'http://inspire.ec.europa.eu/schemas/tn-c/4.0', 'http://inspire.ec.europa.eu/schemas/tn-c/4.0/CableTransportNetwork.xsd')
INSPIRE_TN_RA = _ns('tn-ra', 'http://inspire.ec.europa.eu/schemas/tn-ra/4.0', 'http://inspire.ec.europa.eu/schemas/tn-ra/4.0/RailwayTransportNetwork.xsd')
INSPIRE_TN_RO = _ns('tn-ro', 'http://inspire.ec.europa.eu/schemas/tn-ro/4.0', 'http://inspire.ec.europa.eu/schemas/tn-ro/4.0/RoadTransportNetwork.xsd')
INSPIRE_TN_W = _ns('tn-w', 'http://inspire.ec.europa.eu/schemas/tn-w/4.0', 'http://inspire.ec.europa.eu/schemas/tn-w/4.0/WaterTransportNetwork.xsd')
INSPIRE_TN = _ns('tn', 'http://inspire.ec.europa.eu/schemas/tn/4.0', 'http://inspire.ec.europa.eu/schemas/tn/4.0/CommonTransportElements.xsd')
INSPIRE_UGS = _ns('ugs', 'http://inspire.ec.europa.eu/schemas/ugs/0.0', 'http://inspire.ec.europa.eu/schemas/ugs/0.0/UtilityAndGovernmentalServices.xsd')
INSPIRE_US_EMF = _ns('us-emf', 'http://inspire.ec.europa.eu/schemas/us-emf/4.0', 'http://inspire.ec.europa.eu/schemas/us-emf/4.0/EnvironmentalManagementFacilities.xsd')
INSPIRE_US_GOVSERV = _ns('us-govserv', 'http://inspire.ec.europa.eu/schemas/us-govserv/4.0', 'http://inspire.ec.europa.eu/schemas/us-govserv/4.0/GovernmentalServices.xsd')
INSPIRE_US_NET_COMMON = _ns('us-net-common', 'http://inspire.ec.europa.eu/schemas/us-net-common/4.0', 'http://inspire.ec.europa.eu/schemas/us-net-common/4.0/UtilityNetworksCommon.xsd')
INSPIRE_US_NET_EL = _ns('us-net-el', 'http://inspire.ec.europa.eu/schemas/us-net-el/4.0', 'http://inspire.ec.europa.eu/schemas/us-net-el/4.0/ElectricityNetwork.xsd')
INSPIRE_US_NET_OGC = _ns('us-net-ogc', 'http://inspire.ec.europa.eu/schemas/us-net-ogc/4.0', 'http://inspire.ec.europa.eu/schemas/us-net-ogc/4.0/OilGasChemicalsNetwork.xsd')
INSPIRE_US_NET_SW = _ns('us-net-sw', 'http://inspire.ec.europa.eu/schemas/us-net-sw/4.0', 'http://inspire.ec.europa.eu/schemas/us-net-sw/4.0/SewerNetwork.xsd')
INSPIRE_US_NET_TC = _ns('us-net-tc', 'http://inspire.ec.europa.eu/schemas/us-net-tc/4.0', 'http://inspire.ec.europa.eu/schemas/us-net-tc/4.0/TelecommunicationsNetwork.xsd')
INSPIRE_US_NET_TH = _ns('us-net-th', 'http://inspire.ec.europa.eu/schemas/us-net-th/4.0', 'http://inspire.ec.europa.eu/schemas/us-net-th/4.0/ThermalNetwork.xsd')
INSPIRE_US_NET_WA = _ns('us-net-wa', 'http://inspire.ec.europa.eu/schemas/us-net-wa/4.0', 'http://inspire.ec.europa.eu/schemas/us-net-wa/4.0/WaterNetwork.xsd')
INSPIRE_WFD = _ns('wfd', 'http://inspire.ec.europa.eu/schemas/wfd/0.0', 'http://inspire.ec.europa.eu/schemas/wfd/0.0/WaterFrameworkDirective.xsd')
