from typing import Optional

import re

import gws
import gws.lib.net


class CorsConfig(gws.Config):
    """CORS headers added to responses, to allow cross-origin requests."""

    allowCredentials: bool = False
    """Allow credentials in cross-origin requests."""
    allowHeaders: str = ''
    """Headers allowed in cross-origin requests."""
    allowMethods: str = ''
    """Methods allowed in cross-origin requests."""
    allowOrigin: str = ''
    """Origins allowed to make cross-origin requests."""
    maxAge: int = 5
    """How long the browser caches the CORS preflight response."""


class RewriteRuleConfig(gws.Config):
    """URL rewrite rule."""

    pattern: gws.Regex
    """Regular expression to match the URL path against."""
    target: str
    """Target URL."""
    options: Optional[dict]
    """Additional options."""
    reversed: bool = False
    """Rewrite URLs generated by the server instead of incoming URLs."""


class SSLConfig(gws.Config):
    """SSL certificate and HSTS settings."""

    crt: gws.FilePath
    """Certificate bundle location."""
    key: gws.FilePath
    """Private key file location."""
    hsts: gws.Duration = '365d'
    """Max. age for the Strict-Transport-Security header."""


class WebDirConfig(gws.Config):
    """Directory served over the web."""

    dir: gws.DirPath
    """Directory path."""
    allowMime: Optional[list[str]]
    """Serve only files of these MIME types."""
    denyMime: Optional[list[str]]
    """MIME types not to serve."""


class Config(gws.Config):
    """Web site the server responds to."""

    assets: Optional[WebDirConfig]
    """Directory for assets."""
    cors: Optional[CorsConfig]
    """CORS configuration."""
    contentSecurityPolicy: str = "default-src 'self'; img-src * data: blob:"
    """Content security policy for the site."""
    permissionsPolicy: str = 'geolocation=(self), camera=(), microphone=()'
    """Permissions policy for the site."""
    xFrameOptions: str = 'SAMEORIGIN'
    """Whether the site may be embedded in frames."""
    errorPage: Optional[gws.ext.config.template]
    """Template for HTTP error pages. (deprecated in 8.4)"""
    hostnames: Optional[list[str]]
    """Host names this site responds to, lowercase and without a port."""
    host: str = ''
    """Host name. (deprecated in 8.4)"""
    rewrite: Optional[list[RewriteRuleConfig]]
    """Rewrite rules. (deprecated in 8.4)"""
    rewriteRules: Optional[list[RewriteRuleConfig]]
    """Rules to rewrite incoming URLs and URLs generated by the server."""
    withDefaultRewriteRules: bool = True
    """Add the default rewrite rules for the application."""
    canonicalHost: str = ''
    """Host name for canonical URLs."""
    proxyCount: int = 0
    """Number of proxies in front of the server."""
    root: Optional[WebDirConfig]
    """Directory for static documents."""


DEFAULT_ASSETS_DIR = '/data/assets'
DEFAULT_WEB_DIR = '/data/web'
DEFAULT_REWRITE_RULES = [
    gws.WebRewriteRule(pattern=r'^/$', target='/_/webPage/name/home'),
    gws.WebRewriteRule(pattern=r'^/project/([a-z0-9_-]+)(?=/@|$)', target='/_/webPage/name/project/projectUid/$1'),
    gws.WebRewriteRule(pattern=r'^/_/webPage/name/home$', target='/', reversed=True),
    gws.WebRewriteRule(pattern=r'^/_/webPage/name/project/projectUid/([a-z0-9_-]+)', target='/project/$1', reversed=True),
]


class Object(gws.WebSite):
    ssl: bool
    contentSecurityPolicy: str
    permissionsPolicy: str
    xFrameOptions: str

    def configure(self):
        self.hostnames = self.cfg('hostnames') or []
        p = self.cfg('host')
        if p:
            self.root.config_warning('"web.site.host" is deprecated, use "web.site.hostnames"')
        if p and p != '*':
            self.hostnames = [p]
        
        self.canonicalHost = self.cfg('canonicalHost') or ''
        if not self.canonicalHost and self.hostnames:
            self.canonicalHost = self.hostnames[0]

        self.proxyCount = self.cfg('proxyCount') or 0
        self.ssl = self.cfg('ssl')
        self.corsOptions = self.cfg('cors')
        self.contentSecurityPolicy = self.cfg('contentSecurityPolicy')
        self.permissionsPolicy = self.cfg('permissionsPolicy')
        self.xFrameOptions = self.cfg('xFrameOptions')
        # deprecated
        if self.cfg('errorPage'):
            self.root.config_warning('"web.site.errorPage" is deprecated')
        self.errorPage = self.create_child_if_configured(gws.ext.object.template, self.cfg('errorPage'))

        p = self.cfg('root')
        if p:
            self.staticRoot = gws.WebDocumentRoot(p)
        elif gws.u.is_dir(DEFAULT_WEB_DIR):
            self.staticRoot = gws.WebDocumentRoot(dir=DEFAULT_WEB_DIR)
        else:
            # note: web root must exist
            self.root.config_warning(f'web root {DEFAULT_WEB_DIR!r} does not exist, using temporary directory')
            self.staticRoot = gws.WebDocumentRoot(dir=gws.u.ensure_dir(gws.c.TMP_DIR + '/web'))

        p = self.cfg('assets')
        if p:
            self.assetsRoot = gws.WebDocumentRoot(p)
        elif gws.u.is_dir(DEFAULT_ASSETS_DIR):
            self.assetsRoot = gws.WebDocumentRoot(dir=DEFAULT_ASSETS_DIR)
        else:
            # note: assets root is optional
            self.assetsRoot = None

        self.rewriteRules = []
        p = self.cfg('rewriteRules')
        if not p:
            # deprecated
            p = self.cfg('rewrite')
            if p:
                self.root.config_warning('"web.site.rewrite" is deprecated, use "web.site.rewriteRules"')
        if not p:
            p = []
        for c in p:
            r = gws.WebRewriteRule(c)
            if not gws.lib.net.is_abs_url(r.target):
                # ensure rewriting from root
                r.target = '/' + r.target.lstrip('/')
            self.rewriteRules.append(r)

        if self.cfg('withDefaultRewriteRules', default=True):
            patterns = set(r.pattern for r in self.rewriteRules)
            for c in DEFAULT_REWRITE_RULES:
                if c.pattern not in patterns:
                    self.rewriteRules.insert(0, c)

    def url_for(self, req, path, mode, **params):
        if gws.lib.net.is_abs_url(path):
            return gws.lib.net.add_params(path, params)

        path = self._apply_reverse_rewrite_rules(path)
        if gws.lib.net.is_abs_url(path):
            return gws.lib.net.add_params(path, params)

        path = '/' + path.lstrip('/')
        u = gws.lib.net.parse_url(path)
        u.params.update(params)
        
        if mode == 'relative':
            return gws.lib.net.make_relative_url(u.path, u.params)

        u.scheme = req.scheme
        
        if mode == 'canonical':
            u.hostname = self.canonicalHost
        if not u.hostname:
            u.hostname = req.host
            u.port = req.port
        if not u.hostname:
            raise gws.BadRequestError('no host for an absolute url')

        return gws.lib.net.make_url(u)

    def _apply_reverse_rewrite_rules(self, path):
        for r in self.rewriteRules:
            if not r.reversed:
                continue
            m = re.search(r.pattern, path)
            if not m:
                continue
            # we use nginx syntax $1, need python's \1
            t = r.target.replace('$', '\\')
            return re.sub(r.pattern, t, path)            
        
        return path