"""Docker builder for GWS and QGIS images."""

import os
import sys
import time

sys.path.insert(0, os.path.abspath(os.path.dirname(__file__) + '/../app'))

import gws.lib.cli as cli

USAGE = """
GWS Image Builder
~~~~~~~~~~~~~~~~~
  
    python3 image.py <options>

Options:

    -arch <architecture>
        image architecture (amd64 or arm64) 

    -base <image-name>
        base image, defaults to 'ubuntu'

    -builddir <dir>
        directory to store Dockerfile and assets
        (defaults to GWS_build_root_dir env var)

    -datadir <dir>
        data directory (default projects) to copy to "/data" in the image

    -manifest <path>
        path to MANIFEST.json

    -name <name>
        custom image name 

    -no-cache
        disable cache

    -prep
        prepare the build, but don't run it

    -print
        just print the Dockerfile, do not build

    -vendor <vendor-name>
        vendor name for the Dockerfile

    -version <version>
        override image version

Example:

    python3 image.py -arch amd64 -name my-test-image -datadir my_project/data
"""


class Builder:
    ubuntu_name = 'jammy'
    ubuntu_version = '22.04'

    arch = 'amd64'

    packages_url = 'https://files.gbd-websuite.de'

    gws_user_uid = 1000
    gws_user_gid = 1000
    gws_user_name = 'gws'

    vendor = 'gbdconsult'
    description = 'GWS Server'

    this_dir = os.path.abspath(os.path.dirname(__file__))
    gws_dir = os.path.abspath(f'{this_dir}/..')

    def __init__(self, args):
        self.skip_cache = '_skip_cache_' + str(time.time()).replace('.', '') + '_'

        try:
            self.gws_version = cli.read_file(f'{self.gws_dir}/VERSION')
        except FileNotFoundError:
            self.gws_version = cli.read_file(f'{self.gws_dir}/app/VERSION')
        self.gws_short_version = self.gws_version.rpartition('.')[0]

        self.args = args

        self.arch = args.get('arch') or self.arch
        self.base = args.get('base') or f'ubuntu:{self.ubuntu_version}'

        self.build_root_dir = args.get('builddir') or os.path.abspath(f'{self.gws_dir}/app/__build/docker')

        self.datadir = args.get('datadir') or f'{self.gws_dir}/data'
        self.version = args.get('version') or self.gws_version
        self.vendor = args.get('vendor') or self.vendor
        self.image_name = args.get('name') or f'{self.vendor}/gws-{self.arch}:{self.version}'
        self.context_dir = f'{self.build_root_dir}/{self.image_name}'

        self.apts = lines(cli.read_file(f'{self.this_dir}/apt.lst'))
        self.pips = lines(cli.read_file(f'{self.this_dir}/pip.lst'))

        self.exclude_file = f'{self.gws_dir}/.package_exclude'

        # see https://github.com/wkhtmltopdf/packaging/releases
        self.wkhtmltopdf_package = f'wkhtmltox_0.12.6.1-2.{self.ubuntu_name}_{self.arch}.deb'
        self.wkhtmltopdf_url = f'https://github.com/wkhtmltopdf/packaging/releases/download/0.12.6.1-2/{self.wkhtmltopdf_package}'

    def main(self):
        nc = '--no-cache' if self.args.get('no-cache') else ''
        cmd = f'cd {self.context_dir} && docker build --progress plain -f Dockerfile -t {self.image_name} {nc} .'

        if self.args.get('print'):
            print(self.dockerfile())
            return

        self.prepare()
        if self.args.get('prep'):
            cli.info('prepared, now run:')
            print(cmd)
            return

        cli.run(cmd)
        cli.run(f'rm -fr {self.context_dir}/_skip_cache_*')

    def prepare(self):
        if not os.path.isdir(self.context_dir):
            cli.run(f'mkdir -p {self.context_dir}')

        cli.run(f'rm -fr {self.context_dir}/_skip_cache_*')

        os.chdir(self.context_dir)

        cli.write_file(f'Dockerfile', self.dockerfile())

        if not os.path.isfile(self.wkhtmltopdf_package):
            cli.run(f"curl -sL '{self.wkhtmltopdf_url}' -o {self.wkhtmltopdf_package}")

        cli.run(f'bash {self.gws_dir}/make.sh package . && mv app {self.skip_cache}app')
        if self.datadir:
            cli.run(f'mkdir {self.skip_cache}data')
            cli.run(f'rsync -a --exclude-from {self.exclude_file} {self.datadir}/* {self.skip_cache}data')

    def dockerfile(self):
        df = []
        __ = df.append

        __(f'#')
        __(f'# {self.image_name}')
        __(f'# generated by gbd-websuite/install/image.py')
        __(f'#')
        __(f'FROM --platform=linux/{self.arch} {self.base}')
        __(f'LABEL Description="{self.description}" Vendor="{self.vendor}" Version="{self.version}"')

        __('RUN ' + commands(f'''
            groupadd -g {self.gws_user_gid} {self.gws_user_name}
            useradd -M -u {self.gws_user_uid} -g {self.gws_user_gid} {self.gws_user_name}
        '''))

        apts = ' '.join(f"'{s}'" for s in self.apts)
        pips = ' '.join(f"'{s}'" for s in self.pips)

        __('RUN ' + commands(f'''
            set -x
            apt update
            apt install -y software-properties-common
            apt update
        '''))

        __(f'RUN DEBIAN_FRONTEND=noninteractive apt -y install {apts}')

        __('RUN ' + commands(f'''
            apt-get -y clean
            apt-get -y purge --auto-remove
        '''))

        __(f'RUN pip3 install --no-cache-dir {pips}')

        # this lib causes problems, it should be optional in pendulum
        # see https://github.com/sdispater/pendulum/issues?q=time-machine
        __(f'RUN pip3 uninstall -y time_machine')

        __(f'COPY {self.wkhtmltopdf_package} /{self.wkhtmltopdf_package}')
        __(f'RUN apt install -y /{self.wkhtmltopdf_package} && rm -f /{self.wkhtmltopdf_package}')

        __('RUN ' + commands(f'''
            rm -f /usr/bin/python
            ln -s /usr/bin/python3 /usr/bin/python
            mkdir -p /gws-var
            chown -R {self.gws_user_name}:{self.gws_user_name} /gws-var
        '''))

        __(f'COPY {self.skip_cache}app /gws-app')
        if self.datadir:
            __(f'COPY --chown={self.gws_user_name}:{self.gws_user_name} {self.skip_cache}data /data')

        # GWS_IN_CONTAINER relies on this (should be there, but just in case)
        __(f'RUN touch /.dockerenv')

        __('ENV QT_SELECT=5')
        __('ENV LANG=C.UTF-8')
        __('ENV PATH="/gws-app/bin:/usr/local/bin:${PATH}"')
        __('CMD ["/gws-app/bin/gws", "server", "start"]')

        return '\n'.join(df) + '\n'


###

def main(args):
    b = Builder(args)
    b.main()
    return 0


def commands(txt):
    return ' \\\n&& '.join(lines(txt))


def lines(txt):
    ls = []
    for s in txt.strip().splitlines():
        s = s.strip()
        if s and not s.startswith('#'):
            ls.append(s)
    return ls


def uniq(ls):
    s = set()
    r = []
    for x in ls:
        if x not in s:
            r.append(x)
            s.add(x)
    return r


if __name__ == '__main__':
    cli.main('image.py', main, USAGE)
