#!/usr/bin/env bash

PACKAGE=$1

MODE=Release
if [[ $PACKAGE =~ "debug" ]]; then
   MODE=Debug
fi

echo "BUILDING $PACKAGE, MODE=$MODE"

set -x

cd /
rm -fr /QGIS
cp -r /QGIS_SRC /QGIS
mkdir  /QGIS/_BUILD

git config --global --add safe.directory /QGIS

cd /QGIS/_BUILD

cmake -GNinja -DCMAKE_BUILD_TYPE=$MODE \
-DBINDINGS_GLOBAL_INSTALL=FALSE \
-DBUILD_TESTING=OFF \
-DBUILD_WITH_QT6=FALSE \
-DCMAKE_ENABLE=ON \
-DCMAKE_SKIP_RPATH=NO \
-DCMAKE_VERBOSE_MAKEFILE=TRUE \
-DCPACK_BINARY_DEB=OFF \
-DCPACK_BINARY_FREEBSD=OFF \
-DCPACK_BINARY_IFW=OFF \
-DCPACK_BINARY_NSIS=OFF \
-DCPACK_BINARY_RPM=OFF \
-DCPACK_BINARY_STGZ=OFF \
-DCPACK_BINARY_TBZ2=OFF \
-DCPACK_BINARY_TGZ=OFF \
-DCPACK_BINARY_TXZ=OFF \
-DCPACK_BINARY_TZ=OFF \
-DCPACK_SOURCE_RPM=OFF \
-DCPACK_SOURCE_TBZ2=OFF \
-DCPACK_SOURCE_TGZ=OFF \
-DCPACK_SOURCE_TXZ=OFF \
-DCPACK_SOURCE_TZ=OFF \
-DCPACK_SOURCE_ZIP=OFF \
-DDART_BUILD_WARNING_REPORT_LIMIT=OFF \
-DDART_VERBOSE_BUILD=OFF \
-DDELIVER_CONTINUOUS_EMAIL=Off \
-DDISABLE_DEPRECATED=FALSE \
-DENABLE_COVERAGE=FALSE \
-DENABLE_HANATEST=FALSE \
-DENABLE_LOCAL_BUILD_SHORTCUTS=TRUE \
-DENABLE_MODELTEST=FALSE \
-DENABLE_MSSQLTEST=FALSE \
-DENABLE_MSSQLTEST_CPP=FALSE \
-DENABLE_ORACLETEST=FALSE \
-DENABLE_PGTEST=FALSE \
-DENABLE_SAGA_TESTS=FALSE \
-DENABLE_TESTS=FALSE \
-DFORCE_STATIC_LIBS=FALSE \
-DGENERATE_COVERAGE_DOCS=FALSE \
-DHAS_KDE_QT5_FONT_STRETCH_FIX=FALSE \
-DHAS_KDE_QT5_PDF_TRANSFORM_FIX=FALSE \
-DHAS_KDE_QT5_SMALL_CAPS_FIX=FALSE \
-DPEDANTIC=FALSE \
-DPUSH_TO_CDASH=FALSE \
-DQGIS_INSTALL_SYS_LIBS=TRUE \
-DSIP_GLOBAL_INSTALL=FALSE \
-DUSE_CCACHE=ON \
-DUSE_OPENCL=ON \
-DWERROR=FALSE \
-DWITH_3D=FALSE \
-DWITH_ANALYSIS=FALSE \
-DWITH_APIDOC=FALSE \
-DWITH_ASAN=FALSE \
-DWITH_ASTYLE=FALSE \
-DWITH_AUTH=TRUE \
-DWITH_BINDINGS=TRUE \
-DWITH_CLAZY=FALSE \
-DWITH_COPC=FALSE \
-DWITH_CORE=TRUE \
-DWITH_CRASH_HANDLER=FALSE \
-DWITH_CUSTOM_WIDGETS=FALSE \
-DWITH_DESKTOP=FALSE \
-DWITH_EPT=FALSE \
-DWITH_GRASS7=FALSE \
-DWITH_GRASS8=FALSE \
-DWITH_GSL=FALSE \
-DWITH_GUI=TRUE \
-DWITH_HANA=FALSE \
-DWITH_INTERNAL_LAZPERF=TRUE \
-DWITH_INTERNAL_MDAL=TRUE \
-DWITH_INTERNAL_O2=ON \
-DWITH_INTERNAL_POLY2TRI=TRUE \
-DWITH_OAUTH2_PLUGIN=FALSE \
-DWITH_ORACLE=FALSE \
-DWITH_PDAL=FALSE \
-DWITH_POSTGRESQL=TRUE \
-DWITH_PY_COMPILE=FALSE \
-DWITH_QGIS_PROCESS=FALSE \
-DWITH_QSCIAPI=FALSE \
-DWITH_QSPATIALITE=TRUE \
-DWITH_QT5SERIALPORT=FALSE \
-DWITH_QTWEBKIT=TRUE \
-DWITH_QUICK=FALSE \
-DWITH_QWTPOLAR=FALSE \
-DWITH_SERVER=TRUE \
-DWITH_SPATIALITE=TRUE \
-DWITH_STAGED_PLUGINS=FALSE \
-DWITH_THREAD_LOCAL=TRUE \
..

test $? -eq 0 || exit

cd /QGIS/_BUILD

ninja

test $? -eq 0 || exit

cd /QGIS/_BUILD

rm -fr $PACKAGE
rm -fr $PACKAGE.tar.gz

mkdir -p $PACKAGE/usr

# libraries
cp -r output/lib $PACKAGE/usr

# server
mkdir -p $PACKAGE/usr/bin
cp output/bin/qgis_mapserv.fcgi $PACKAGE/usr/bin

# python (qgis package only)
mkdir -p $PACKAGE/usr/lib/python3/dist-packages
cp -r output/python/qgis $PACKAGE/usr/lib/python3/dist-packages

# resources (no depth)
mkdir -p $PACKAGE/usr/share/qgis/resources
cp ../resources/* $PACKAGE/usr/share/qgis/resources
cp -r ../resources/server $PACKAGE/usr/share/qgis/resources

# svg's
cp -r  ../images/svg $PACKAGE/usr/share/qgis

# license
cp ../COPYING $PACKAGE/usr/lib
    
# delete lib symlinks
find $PACKAGE -type l -exec rm -fr {} \;

# delete python caches
find $PACKAGE -depth -name __pycache__ -exec rm -fr {} \;

tar -czf $PACKAGE.tar.gz $PACKAGE

mv $PACKAGE.tar.gz /COMPILE

set +x

echo "CREATED /COMPILE/$PACKAGE.tar.gz"
